#include <iostream>
#include "Ciudad.h"
using namespace std;

Ciudad matrizMapa1Cuadrado[9][9] = {
	//Arequipa									 Cusco								     Chiclayo									Iquitos									  Juliaca									Lima								   Piura								   Puerto Maldonado									  Trujillo
	/*Arequipa				*/		{ Ciudad("Arequipa", "Arequipa", 1),	     Ciudad("Arequipa", "Cusco", 1),         Ciudad("Arequipa", "Chiclayo", 1),         Ciudad("Arequipa", "Iquitos", 1),         Ciudad("Arequipa", "Juliaca", 1),         Ciudad("Arequipa", "Lima", 1),         Ciudad("Arequipa", "Piura", 1),         Ciudad("Arequipa", "Puerto Maldonado", 1),         Ciudad("Arequipa", "Trujillo", 1)				},
	/*Cusco					*/		{ Ciudad("Cusco", "Arequipa", 1),			 Ciudad("Cusco", "Cusco", 1),			 Ciudad("Cusco", "Chiclayo", 0),            Ciudad("Cusco", "Iquitos", 1),            Ciudad("Cusco", "Juliaca", 1),            Ciudad("Cusco", "Lima", 1),            Ciudad("Cusco", "Piura", 1),            Ciudad("Cusco", "Puerto Maldonado", 0),            Ciudad("Cusco", "Trujillo", 1)				},
	/*Chiclayo				*/		{ Ciudad("Chiclayo", "Arequipa", 1),		 Ciudad("Chiclayo", "Cusco",1),          Ciudad("Chiclayo", "Chiclayo", 0),         Ciudad("Chiclayo", "Iquitos", 1),         Ciudad("Chiclayo", "Juliaca", 1),         Ciudad("Chiclayo", "Lima", 0),         Ciudad("Chiclayo", "Piura", 1),         Ciudad("Chiclayo", "Puerto Maldonado", 0),         Ciudad("Chiclayo", "Trujillo", 1)				},
	/*Iquitos				*/		{ Ciudad("Iquitos", "Arequipa", 1),			 Ciudad("Iquitos", "Cusco", 1),          Ciudad("Iquitos", "Chiclayo", 0),          Ciudad("Iquitos", "Iquitos", 1),          Ciudad("Iquitos", "Juliaca", 1),          Ciudad("Iquitos", "Lima", 0),		   Ciudad("Iquitos", "Piura", 1),          Ciudad("Iquitos", "Puerto Maldonado", 0),          Ciudad("Iquitos", "Trujillo", 1)				},
	/*Juliaca				*/		{ Ciudad("Juliaca", "Arequipa", 1),			 Ciudad("Juliaca", "Cusco", 1),			 Ciudad("Juliaca", "Chiclayo", 0),          Ciudad("Juliaca", "Iquitos", 1),          Ciudad("Juliaca", "Juliaca", 1),          Ciudad("Juliaca", "Lima", 0),		   Ciudad("Juliaca", "Piura", 1),          Ciudad("Juliaca", "Puerto Maldonado", 0),          Ciudad("Juliaca", "Trujillo", 1)				},
	/*Lima					*/		{ Ciudad("Lima", "Arequipa", 1),			 Ciudad("Lima", "Cusco", 1),			 Ciudad("Lima", "Chiclayo", 1),             Ciudad("Lima", "Iquitos", 0),             Ciudad("Lima", "Juliaca", 0),             Ciudad("Lima", "Lima", 1),			   Ciudad("Lima", "Piura", 0),             Ciudad("Lima", "Puerto Maldonado", 1),             Ciudad("Lima", "Trujillo", 0)					},
	/*Piura					*/		{ Ciudad("Piura", "Arequipa", 1),			 Ciudad("Piura", "Cusco", 1),			 Ciudad("Piura", "Chiclayo", 1),            Ciudad("Piura", "Iquitos", 1),            Ciudad("Piura", "Juliaca", 1),            Ciudad("Piura", "Lima", 1),			   Ciudad("Piura", "Piura", 1),            Ciudad("Piura", "Puerto Maldonado", 1),            Ciudad("Piura", "Trujillo", 1)				},
	/*Puerto Maldonado		*/		{ Ciudad("Puerto Maldonado", "Arequipa", 1), Ciudad("Puerto Maldonado", "Cusco", 0), Ciudad("Puerto Maldonado", "Chiclayo", 0), Ciudad("Puerto Maldonado", "Iquitos", 0), Ciudad("Puerto Maldonado", "Juliaca", 0), Ciudad("Puerto Maldonado", "Lima", 1), Ciudad("Puerto Maldonado", "Piura", 0), Ciudad("Puerto Maldonado", "Puerto Maldonado", 1), Ciudad("Puerto Maldonado", "Trujillo", 0)		},
	/*Trujillo				*/		{ Ciudad("Trujillo", "Arequipa", 1),		 Ciudad("Trujillo", "Cusco",1),			 Ciudad("Trujillo", "Chiclayo", 1),         Ciudad("Trujillo", "Iquitos", 1),         Ciudad("Trujillo", "Juliaca", 1),         Ciudad("Trujillo", "Lima", 0),         Ciudad("Trujillo", "Piura", 1),         Ciudad("Trujillo", "Puerto Maldonado", 0),         Ciudad("Trujillo", "Trujillo", 1)				},
};
